### ISSUE TITLE
ERROR Could not bind to (u0.0.0.0, u8000)

### ISSUE THREAD

**Issue by sorbing** [Eugeny/ajenti-v#118]
I installed the Ajenti on Ubuntu 14.04 x64 and when I run `sudo ajenti-panel -v` - I get error:

```
13.10.2014 14:09 core.py:99    INFO  Starting server on (u'0.0.0.0', u'8000')
13.10.2014 14:09 core.py:121   ERROR Could not bind to (u'0.0.0.0', u'8000')
```

I have verified that port 8000 is free:

```
netstat -tlnp | grep 8000
sudo nmap -sT -O localhost
```

Prompt in what could be the problem? Thanks.

**Comment by davidblaesing** [comment]
same issue here

**Comment by juslintek** [comment]
Me too on Debian 8; But while ajento was on in confi.json I changed port to 10000 saved run ajenti-panel-v and everything was fine. Then restarted after ajenti-panel -v same error. Again changed in config.json port back to 8000 saved run ajenti-panel-v ant its binding the address and I get the green light, but when I try to connect to web panel, nothing happens, here is what traceback I get:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_soc                                                                                       ket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f92819ee7d0: <bound method SocketIOServer.wrap_socket_and_handle                                                                                        of <SocketIOServer at 0x7f92819db810 fileno=6 address=10.0.2.4:10000>>(<socket at                                                                                        0x7f92819f8fd0 fileno=12 sock=10.0.2.4:, ('192.168.0.196', 57723))> failed with                                                                                        NameError
