### ISSUE TITLE
Crash on using same folder with 2 different domain[host]

### ISSUE THREAD

**Issue by davodm** [Eugeny/ajenti-v#280]
Hi,
When I want to create another website with the same folder which used it shows this error:

Crashed

org.freedesktop.DBus.Error.ServiceUnknown: The name :1.0 was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/vh/main.py", line 259, in save
    self.manager.update_configuration()
  File "/var/lib/ajenti/plugins/vh/api.py", line 363, in update_configuration
    gevent.joinall(greenlets)
  File "/var/lib/ajenti/plugins/vh/api.py", line 354, in __runall
    try:
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.0 was not provided by any .service files

The bug report is attached.
[ajenti-v-bug-report.txt](https://github.com/Eugeny/ajenti-v/files/1699445/ajenti-v-bug-report.txt)

**Comment by davodm** [comment]
After restarting the server it's got ok without any problem!
